### ISSUE TITLE
Option to customize conventions

### ISSUE THREAD

**Issue by marcusds** [merkle-open/stylelint-bem#18]
## Type of issue

* Feature request

This plugin is using the getbem.com standard instead of the BEM standard from bem.info (which is from the original creators of BEM), it would nice if the customize the BEM conventions to match what we are targeting. Thanks.

https://en.bem.info/methodology/naming-convention/

**Comment by pdaus1405** [comment]
I find this feature also good 👍🏻

**Comment by ernscht** [comment]
Sorry, I've neglected this repo terribly. Thanks for the reminder.
I'll try to take some time this weekend.

**Comment by pdaus1405** [comment]
No work? is the package died?

**Comment by MatheusRich** [comment]
@pdaus1405 The last commit was dec/2020, I think it's not dead.

**Comment by pdaus1405** [comment]
but some comments, wishes and pr's and no movement

**Comment by jantimon** [comment]
I am using this plugin in multiple projects and it works well.  
Adding now tons of option will increase the complexity for configuration and maintenance.

That's the reason why we are cautious to add new options unless they are solving a common problem.

**Comment by ernscht** [comment]
Sorry guys for the late replies. And thanks for the feature request.

In addition to Jan's answer:
As you can see from the examples, we didn't just take over rules, but also extended them. The Linting Tool represents our idea of how the class names should be structured. This has developed over the years.
For example, we decided to only allow lower case letters. On the one hand this is very readable, on the other hand it's easy to lint. 

We are aware that this stylelint plugin cannot be used to lint different bem naming conventions, which is why we have decided to publish the package scoped. We want to offer a simple, clear plugin and keep the complexity small to remain maintainable.

Do you know this stylelint plugin [stylelint-selector-bem-pattern](https://github.com/simonsmith/stylelint-selector-bem-pattern)?
It offers configuration options for different naming conventions. It didn't match our needs, but maybe it goes in the direction you want?

**Comment by pdaus1405** [comment]
thank you, i know the plugin.
unfortunately it is dead and can no longer cope with the current stylelint version.

**Comment by ernscht** [comment]
Closing, due to the fact, that this is an optiniated scoped stylelint plugin to follow our idea of how the class names should be structured.
We will not invest additional development time in ideas that generate work for us but add little value. PR's we would of course like to discuss.
